// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8rNZ-rlvs4Q9djvTnk77EjwGDL9UFIzc',
    appId: '1:1025899245712:web:543c870afbd6de41ca6815',
    messagingSenderId: '1025899245712',
    projectId: 'crimereport-29782',
    authDomain: 'crimereport-29782.firebaseapp.com',
    storageBucket: 'crimereport-29782.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCplq8IsQsN44AxLo6NVfTZD_074Wcf_5A',
    appId: '1:1025899245712:android:34e0e1f73d228cd5ca6815',
    messagingSenderId: '1025899245712',
    projectId: 'crimereport-29782',
    storageBucket: 'crimereport-29782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5mNcuQGrkBDzfERqjraSn_BfcNamUYhc',
    appId: '1:1025899245712:ios:e2b0a63e3dfdc21dca6815',
    messagingSenderId: '1025899245712',
    projectId: 'crimereport-29782',
    storageBucket: 'crimereport-29782.firebasestorage.app',
    iosBundleId: 'com.report.reportcrime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5mNcuQGrkBDzfERqjraSn_BfcNamUYhc',
    appId: '1:1025899245712:ios:49bc54d21fdcacedca6815',
    messagingSenderId: '1025899245712',
    projectId: 'crimereport-29782',
    storageBucket: 'crimereport-29782.firebasestorage.app',
    iosBundleId: 'com.example.reportcrime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8rNZ-rlvs4Q9djvTnk77EjwGDL9UFIzc',
    appId: '1:1025899245712:web:43326de1cfbe8852ca6815',
    messagingSenderId: '1025899245712',
    projectId: 'crimereport-29782',
    authDomain: 'crimereport-29782.firebaseapp.com',
    storageBucket: 'crimereport-29782.firebasestorage.app',
  );
}
